export const SET_FOR_USER_EXPENSE_REPORTS = "set_for_user_expense_reports";
export const SET_FROM_USER_EXPENSE_REPORTS = "set_from_user_expense_reports";
export const SET_SINGLE_EXPENSE_REPORT_FROM_USER_REQUESTS = "set_single_expense_report_from_user_requests";